config/routes.rb
Share::Application.routes.draw do

  get "users/index"

  devise_for :users

  resources :user_messages
  resources :users, :only => [:index, :show]
  resources :appeals, :only => [:index, :create]
  resources :pending_appeals, :only => [:index, :update, :destroy]
  resources :friends, :only => [:index]

   root :to => 'user_messages#index'

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	before_filter :authenticate_user!

	def index
		@friends = Appeal.where("user_id = :user or receiver_id = :user and is_accepted = true", user: current_user.id)
		# received_requests = Appeal.where("receiver_id = :user and is_accepted = true", user: current_user.id).map(&:user_id)
		# @friends = User.where(:id => [send_requests + received_requests])
	end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<div class="page-header">
    <h1>My Friends</h1>
</div>
<% if @friends %>
	<div class="row">
		<div class="col-lg-6">
			<div class="bs-example table-responsive">
				<table class="table table-striped table-bordered table-hover">
					<tbody>
						<% @friends.each do | friend | %>
							<% if friend.user == current_user %>
								<tr>
									<td><%= friend.receiver.name %></td>
									<td><%= friend.receiver.email %></td>
									<td>
										<%= link_to "Remove from Friends", pending_appeal_path(friend), :method => :delete, :confirm => 'Are you sure?', :class => "btn btn-danger btn-xs" %>
									</td>
								</tr>
							<% else %>
								<tr>
									<td><%= friend.user.name %></td>
									<td><%= friend.user.email %></td>
									<td>
										<%= link_to "Remove from Friends", pending_appeal_path(friend), :method => :delete, :confirm => 'Are you sure?', :class => "btn btn-danger btn-xs" %>
									</td>
								</tr>
							<% end %>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
<% else %>
	<div class="row">
		<div class="col-lg-6">
      <div class="well">
  			<p>You don't have any friend. You can add friends <%= link_to "here", users_path %></p>
  		</div>
    </div>
	</div>
<% end %>