config/routes.rb
Share::Application.routes.draw do

  get "users/index"

  devise_for :users

  resources :user_messages
  resources :users, :only => [:index, :show]
  resources :appeals, :only => [:index, :create]
  resources :pending_appeals, :only => [:index, :update, :destroy]
  resources :friends, :only => [:index]

   root :to => 'user_messages#index'

end

app/models/user_message.rb
class UserMessage < ActiveRecord::Base
  
  attr_accessible :message, :image, :remote_image_url, :remove_image
  mount_uploader :image, ImageUploader

  validates :message, presence: true, length: { maximum: 140 }
  validates_with UniqueMessageValidator
  validates :user, :presence => true

  # Relationships
  belongs_to :user

  before_destroy :remove_image
  after_destroy :remove_id_directory

  def remove_id_directory
    FileUtils.remove_dir("#{Rails.root}/public/#{ImageUploader.store_dir}/user_message/image/#{self.id}", :force => true)
  end

end

app/controllers/user_messages_controller.rb
class UserMessagesController < ApplicationController

  before_filter :authenticate_user!

 def get_user_messages
    send_requests = Appeal.where("user_id = :user and is_accepted = true", user: current_user.id).map(&:receiver_id)
    received_requests = Appeal.where("receiver_id = :user and is_accepted = true", user: current_user.id).map(&:user_id)
    @user_messages = UserMessage.where(:user_id => [send_requests + received_requests << current_user.id ]).order("created_at DESC")
  end

  def index
    @user_messages = get_user_messages
    @user_message = UserMessage.new
  end

  def new
    @user_message = UserMessage.new
  end

  def create
    @user_message = UserMessage.new(params[:user_message])
    @user_message.user = current_user
    if @user_message.save
      user_messages = get_user_messages
      flash[:notice] = 'Great, we will spread yours words!'
      redirect_to(action: :index) unless request.xhr?
    else
      flash[:error] = 'Hmm,it seems you forgot write something'
      render(:action => :new) unless request.xhr?
    end

    # respond_to do |format|  
    #   if @user_message.save
    #     user_messages = get_user_messages
    #     format.html { redirect_to(@user_message, :notice => 'Great, we will spread yours words!') }  
    #     format.js 
    #   else
    #     format.html { render :action => "new", :error => 'Hmm,it seems you forgot write something' }  
    #     format.js
    #   end
    # end
  end

  def show
    @user_message = current_user.user_messages.find(params[:id])
  end

  def edit
    @user_message = current_user.user_messages.find(params[:id])
  end

  def update
    @user_message = current_user.user_messages.find(params[:id])
    if @user_message.update_attributes(params[:user_message])
      flash[:notice] = 'Message updated!'
      redirect_to @user_message
    else
      render :action => :edit
    end
  end

  def destroy
    @user_message = current_user.user_messages.find(params[:id])
    if @user_message.destroy
        user_messages = get_user_messages
        flash[:notice] = 'Message destroyed!'
        redirect_to(action: :index) unless request.xhr?
   #     flash[:notice] = 'Message destroyed!'
   #     redirect_to action: :index
    end
  end

end

app/helpers/user_messages_helper.rb
module UserMessagesHelper
end

app/views/user_messages/_form.html.erb
<%= form_for @user_message, :html => { :class => 'form-horizontal bs-example', :multipart => true } do |f| %>
  
  <% if @user_message.errors.any? %>
    <div id="error_explanation">
      <h2>Oops something goes wrong:  <%= pluralize(@user_message.errors.count, "error") %></h2>
      <ul>
      <% @user_message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :message, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :message, :class => "text_area form-control", :size => "50x5" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :remote_image_url, " Image from URL ", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :remote_image_url, :class => "form-control"%>
    </div>
  </div>
  <br/>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_messages_path, :class => 'btn' %>
  </div>
<% end %>

app/views/user_messages/_form_ajax.html.erb
<%= form_for @user_message, :remote => true, 
:html => { :class => 'form-horizontal bs-example', :multipart => true } do |f| %>
  <div id= "user_message_errors" style="display:none"></div>
  <div class="well">
    <div class="control-group">
      <%= f.label :message, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :message, :class => "text_area form-control", rows: 2, cols: 2, placeholder: "write something..." %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :remote_image_url, " Image from URL ", :class => 'control-label' %>
      <div class="controls"> 
        <%= f.text_field :remote_image_url, :class => "form-control input-sm"%> 
      </div>
    </div>
    <div class="control-group">
      <%= f.label :image, "or local image" , :class => 'control-label' %>
      <div class="controls"> <%= f.file_field :image %> </div>
    </div>

    <br/>
    <div class="form-actions">
      <%= f.submit "Share it", :class => 'btn btn-primary btn-xs'%>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  user_messages_path, :class => 'btn btn-danger btn-xs' %>
    </div>
  </div>
<% end %>

app/views/user_messages/_user_messages.html.erb
  <% if @user_messages %>
    <% @user_messages.each do |user_message| %>
      <div class="well well-sm ">

        <p> 
          <span class="pull-left" style="padding: 6px;">
            <%= image_tag avatar_url(user_message.user) %>
          </span>
          <span class="badge pull-right">
            <%= time_ago_in_words(user_message.created_at) %>
           </span>
          <div>
            <%= link_to  user_path(user_message.user), :method => :get , :class => "user_name" do %> 
              <%= user_message.user.name %> 
            <% end %>
            <br/>
            <%= user_message.user.email %>
          </div> 
        </p>
        
        <p>
          <%= auto_link(user_message.message, :html => { :target => '_blank' }) %>
          <%= image_tag user_message.image_url(:thumb).to_s if user_message.image_url %> 
        </p>
      
        <div class="options">
          <%= link_to user_message_path(user_message)  do %>
              <i class="fa fa-eye "> Details </i>
          <% end %>
          &nbsp; &nbsp;
          <%= link_to edit_user_message_path(user_message) do %>
              <i class="fa fa-edit"> Edit </i>
          <% end %>
          &nbsp; &nbsp;
          <%= link_to user_message_path(user_message),
            remote: true,
            :method => :delete,
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } do %>
            <i class="fa fa-eraser"> Delete </i>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="well well-sm">
      <p>You don't have any message yet. Start writting something !</p>
    </div>
  <% end %>

app/views/user_messages/create.js.erb
<% if @user_message.errors.any? -%>
  /*Hide the flash notice div*/
 
  /*Update the html of the div user_message_errors with the new one*/
    <% @user_message.errors.full_messages.each do |msg| %>
     $("#user_message_errors").html("<li><%= msg %></li>");
    <% end %>

  /*Show the div user_message_errors*/
  $("#user_message_errors").show(300);
<% else -%>
  /*Hide the div user_message_errors*/
  $("#user_message_errors").hide(300);

  /*Clear the entire form*/
  $(":input:not(input[type=submit])").val("");

  /*Replace the html of the div user_message_lists with the updated new one*/
  $("#user_messages_list").html("<%= j( render("user_messages/user_messages") ) %>");
<% end -%>

app/views/user_messages/destroy.js.erb
$("#user_messages_list").html("<%= j( render("user_messages/user_messages") ) %>");

app/views/user_messages/edit.html.erb
<%- model_class = UserMessage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_messages/index.html.erb
<%- model_class = UserMessage -%>

<div class="page-header">
  <h1>Timeline</h1>
</div>

  <div class="panel panel-success message_container">
    
    <div class="panel-body">
       <div id="user_message_form" class="message_container">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">New message</h3>
            </div>
            <div class="panel-body">
              <%= render :partial => 'form_ajax' %>
            </div>
          </div>
       
        </div>
       <div id="user_messages_list"><%= render :partial => "user_messages" %></div>
    </div>
      
  </div>

app/views/user_messages/new.html.erb
<%- model_class = UserMessage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_messages/show.html.erb
<%- model_class = UserMessage -%>

  <div class="well well-sm ">
    <p> 
      <span class="pull-left" style="padding: 6px;">
        <%= image_tag avatar_url(@user_message.user) %>
      </span>
      <span class="badge pull-right">
        <%= time_ago_in_words(@user_message.created_at) %>
       </span>
      <div>
        <%= link_to  user_path(@user_message.user), :method => :get do %> 
          <%= @user_message.user.name %> 
        <% end %>
        <br/>
        <%= @user_message.user.email %>
      </div> 
    </p>
    
    <p>
      <%= auto_link(@user_message.message, :html => { :target => '_blank' }) %>
    </p>
    <%= image_tag @user_message.image_url(:medium).to_s if @user_message.image_url %> 
  <p>

    <%= link_to user_messages_path do %>
      <i class="fa fa-arrow-left"> Back </i>
    <% end %> &nbsp; &nbsp;
    <%= link_to edit_user_message_path(@user_message) do %>
      <i class="fa fa-edit"> Edit </i>
    <% end %> &nbsp; &nbsp;

    <%= link_to user_message_path(@user_message),
          :method => :delete,
          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } do %>
      <i class="fa fa-eraser"> Delete </i>
    <% end %>
  </p>
</div>