config/routes.rb
Share::Application.routes.draw do

  get "users/index"

  devise_for :users

  resources :user_messages
  resources :users, :only => [:index, :show]
  resources :appeals, :only => [:index, :create]
  resources :pending_appeals, :only => [:index, :update, :destroy]
  resources :friends, :only => [:index]

   root :to => 'user_messages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Share" %></title>
   

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->

    <%= javascript_include_tag "application" %>
     <%= csrf_meta_tags %>
  </head>

  <body>

     <!-- Navbar - top
    ================================================== -->
    <div class="navbar navbar-default navbar-fluid-top">
      <div class="container">
        <div class="navbar-header">
          <a href="../" class="navbar-brand">Share it!</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" 
          data-target="#navbar-main">
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li><%= link_to 'All messages', user_messages_path %></li>
            <% if user_signed_in? %>
            <li><%= link_to 'Find Users', users_path %></li>
            <li><%= link_to 'Friends', friends_path %></li>
            <li><%= link_to 'Send Requests', appeals_path %></li>
            <li class="dropdown open">
              <%=link_to pending_appeals_path, remote: true, 
              :class =>"dropdown-toggle",
              :id =>"appeals", 'data-toggle'=>"dropdown" do -%>
                <i class="fa fa-bell"> <span class="caret"></span> </i>
              <% end -%>
              <ul class="dropdown-menu" aria-labelledby="appeals" id="appeals_list" style="display:none;">
                <li></li>
              </ul>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
              <li>
                <%= link_to edit_user_registration_path, :method => :get do %>
                   Edit Profile ( <%= current_user.name %> )
                <% end %>
              </li>
              <% end %>
              <li> 
                <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> 
                <% end %>
              </li>
              <% if !user_signed_in? %>
                 <li> <%= link_to "Sign up", new_user_registration_path %> </li>
                 <li> <%= link_to "Sign in", new_user_session_path %> </li>
              <% end %>
          </ul>
        </div>
      </div>
    </div>


  <div class="container">
    
      <!-- Flash messages 
        ================================================== -->
      <div id="flash_notice" style="display:none"></div>
      <div id="flash_error" style="display:none"></div>
      <% if flash[:notice] -%>
        <div class="alert alert-dismissable alert-success">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <p class='notice'><%=h flash[:notice] %></p>
       </div>
     <% end %>

     <% if flash[:error]%>
        <div class="alert alert-dismissable alert-danger">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <p class='notice'><%=h flash[:error] %></p>
       </div>
     <% end%>

      <%= yield %>
      
      <!-- Footer 
        ================================================== -->
      <footer>
        <div class="row">
          <div class="col-lg-12">
            <p>
              Made by <a href="http://erlinisquintana.me">Erlinis Quintana</a>. Contact her at <a href="mailto:erlinis.quintana@koombea.com">erlinis.quintana@koombea.com</a>.
            </p>
            <p>Code licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License v2.0</a>.</p>
          </div>
        </div>
      </footer>

  </div>

  </body>
</html>